project:
  name: financial-fraud-detection

deploy:
  airflow:
    image: astro-runtime:3.1-3
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./data:/usr/local/airflow/data
      - ./scripts:/usr/local/airflow/scripts
      - ./.kaggle:/root/.kaggle
